import { ValidationError } from '../errors';
import { OutputType } from '../types';

/**
 * Validates if the value is a valid UUID.
 *
 * @param value The value to validate.
 * @param rules An object that can contain the properties:
 *  - `version`: specifies the UUID version (1, 2, 3, 4, or 5).
 *  - `provider`: specifies the provider, either "standard" for RFC 4122 UUIDs
 *    or "oracle" for Oracle UUIDs. You can also pass a boolean
 *    to assume version 4 and "standard" provider by default.
 * @param output The expected validation output type, of type {@link OutputType}.
 *  - `record`: Returns an array of strings representing the validation errors.
 *  - `exception`: Throws an error with validation messages.
 *
 * @returns An array of strings representing the validation errors.
 *
 * @example
 * const errors = validateIsUUID("12345678-1234-5678-1234-567812345678");
 * console.log(errors);
 * // []
 *
 * const errors = validateIsUUID("12345678-1234-5678-1234-567812345678", {
 *   version: 4,
 *   provider: "standard",
 * });
 * console.log(errors);
 * // []
 *
 * const errors = validateIsUUID("12345678-1234-5678-1234-567812345678", {
 *   provider: "oracle",
 * });
 * console.log(errors);
 * // []
 */
export function validateIsUUID(
  value: any,
  rules: { version?: number; provider?: 'standard' | 'oracle' } | boolean = {
    provider: 'standard',
  },
  output: OutputType = 'record'
): string[] {
  // Returns an array of errors or nothing if it throws an exception
  const errors: string[] = [];

  if (value === null || value === undefined) {
    return errors;
  }

  if (typeof value === 'string' && value.trim() === '') {
    const errorMessage = 'The UUID cannot be an empty string.';
    if (output === 'exception') {
      throw new ValidationError(errorMessage);
    }
    errors.push(errorMessage);
    return errors;
  }

  // If rules is boolean, assume version 4 by default and "standard" provider
  const version = typeof rules === 'boolean' ? 4 : rules.version;
  const provider = typeof rules === 'boolean' ? 'standard' : (rules.provider ?? 'standard');

  // Verify that the value is a text string
  if (typeof value !== 'string') {
    errors.push('Must be a text string.');
  }

  // Verify UUID structure (exact length)
  if (value.length !== 36) {
    errors.push('The UUID must be exactly 36 characters long.');
  }

  // Specific validation for RFC 4122 (standard UUID)
  if (provider === 'standard') {
    if (version !== undefined && ![1, 2, 3, 4, 5].includes(version)) {
      errors.push('The UUID version must be 1, 2, 3, 4, or 5.');
    }

    const versionPattern = version ? `[${version}]` : `[1-5]`;
    const uuidRegex = new RegExp(
      `^[0-9a-f]{8}-[0-9a-f]{4}-${versionPattern}[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`,
      'i'
    );

    if (!uuidRegex.test(value)) {
      errors.push(
        version
          ? `Must be a valid UUID of version ${version} with a correct variant.`
          : 'Must be a valid UUID with a version between 1 and 5 and a correct variant.'
      );
    }
  }

  // Specific validation for Oracle UUIDs
  if (provider === 'oracle') {
    const oracleUuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

    if (!oracleUuidRegex.test(value)) {
      errors.push('Must be a valid UUID generated by Oracle.');
    }
  }

  // Depending on the 'output' option, we handle the output
  if (output === 'exception' && errors.length > 0) {
    throw new ValidationError(errors.join('\n'));
  }

  return errors;
}
